baseURL = "/"
languageCode = "en-us"
title = "Dignity and Debt"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = ""
paginate = 5

[imaging]
resampleFilter = "box"
quality = 70
anchor = "smart"

[params]
  google_analytics_id=""
  hideFooter=false
  includeBootstrapJs=true
  containerMaxWidth=1200
  showActiveNav=true
  paginage=5

[[menu.main]]
	name = "About"
	url = "/about/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "Meetings"
    url = "/meetings/"
    weight = 3

# [[menu.main]]
#    name = "News"
#    url = "/news/"
#    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
